[env]
RUST_BACKTRACE = "1"

[tasks.ci]
dependencies = ["check", "lint", "fmt-check", "build", "doc", "test", "schema"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.schema]
command = "cargo"
args = ["run", "--example", "schema"]

[tasks.build]
command = "cargo"
args = ["build", "-q", "--all-targets"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "-q", "--all", "--", "--check"]
dependencies = ["install-rustfmt"]

[tasks.check]
command = "cargo"
args = ["check", "-q", "--all-targets", "--locked"]

[tasks.doc]
command = "cargo"
args = ["doc", "-q", "--no-deps"]

[tasks.lint]
command = "cargo"
args = ["clippy", "-q", "--all-targets"]
dependencies = ["install-clippy-any"]

[tasks.optimize]
script = '''
docker run --rm -v ${PWD}:/code \
  	--mount type=volume,source="$(basename ${PWD})_cache",target=/code/target \
  	--mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  	cosmwasm/rust-optimizer:0.11.5
'''
